### PR TITLE
Make sass

### PR DESCRIPTION
**Pull request by Vidmasas**
Hey, I am not sure if I am doing it right so I want if you could tell me if I am on a right path when making variables... I'm taking an example from Oberlo style guides.

### CODE REVIEW

**Comment by alynioke** [comment]
also paddings: i se you defined for example those variables:
```
$padding-commits-content:                   12px 24px;
$padding-commits-view-all:                  24px 24px 0;
```
and i suppose you're gonna use them as:
```
.commits-content {
  padding: $padding-commits-content;  
}
.commits-view-all {
  padding: $padding-commits-view-all;
}
```

I'm not sure about class names, they are just for example. 

So this is not optimal, because you see, you can use these variables ONLY when padding are 100% the same as they. E.g. imagine, if we have another element with padding 12px 24px 0. We can't reuse any variables then. Because of that, we rarely put the whole padding value (even tho it's also possible). Usually, we define only ONE of those numbers as variable. Looks how  it could be improved:
```
$padding-small: 12px;
$padding-big: 24px;
```

Then use it: 
```
.commits-content {
  padding: $padding-small $padding-big;  
}
.commits-view-all {
  padding: $padding-big $padding-big 0;
}
```

now you can create any combinations with those variables! much more flexible! Now i can define any combo of 12 and 24. E.g. `padding: $padding-small $padding-big 0`, which we originally couldn't do.

So in your case i would write out all *unique* values of paddings, and try to put them in variables. I think it's only about 7 values (so will be 7 variables) - 
image
All the other values are either repeating them, or are close to them! E.g. 8px could be substituted by 7px variable !

**Comment by alynioke** [comment]
P.s. i'm not sure about `package.json` and how to make it run, i didn't check it, so not commenting anything.

**Comment by Vidmasas** [comment]
> I can even say you don't have to define variable for 24px. Let's say you gonna name some `$space-small: 12px;` Then you can use `padding: $space-small* 2;` where you need 24px!

Great idea! But I am not sure on how often should I use a multiplier. I add `2px` and `2%` as the smallest variable so I could multiply it as many times as I want, but I am not sure if it is a good practice since my code will have a multiplier on each line. It would be nice to know how small should I go and how often multipliers should be used.

**Comment by Vidmasas** [comment]
P.s. thank you a lot for this PR review! Very detailed and it eliminated 90% of my doubts when I have started this SCSS file 😅

**Comment by alynioke** [comment]
> > I can even say you don't have to define variable for 24px. Let's say you gonna name some `$space-small: 12px;` Then you can use `padding: $space-small* 2;` where you need 24px!
> 
> Great idea! But I am not sure on how often should I use a multiplier. I add `2px` and `2%` as the smallest variable so I could multiply it as many times as I want, but I am not sure if it is a good practice since my code will have a multiplier on each line. It would be nice to know how small should I go and how often multipliers should be used.

Good question. It's a creative process, with no strict rules I would say. You understand yourself, defining 2px, and multiplying each time is not optimal. So you seek balance. Usually designer can suggest the most common spacing values, and you define them based on designer explanation of grid. Here's example of Oberlo's: 
image

$space-xs = 8, $space-sm = 16. But we define them separately. Why? If we use 16 very frequently, if it's one of mostly used spacing, then it will look ugly in code to multiply $space-xs * 2 each time (even tho mathematically we can). You could think about it the same way as of JavaScript variables. If you see some expression like a * 2 many times, probably you create a variable to store the result ;)

**Comment by Vidmasas** [comment]
Seems clear, but what about a percentage expressions? It seems Oberlo is not using any percentages?

**Comment by alynioke** [comment]
consider best :)

**Comment by Vidmasas** [comment]
I guess it should be more or less fine. Not all are added, but I guess the logic is fine and I can start implementing?

**Pull request closed without merging**
